name: Update score.yaml and Open PR

on:
  workflow_dispatch:
    inputs:
      port_context:
        required: true
        description: Includes the action's run id

jobs:
  update-score-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update score.yaml file using yq
      run: |
        yq eval '.resources.storage.type = "s3"' -i score.yaml

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add score.yaml
        git commit -m "Update score.yaml with storage type s3"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GH_TOKEN }}
        branch: update-score-file-branch
        commit-message: Update score.yaml with storage type s3
        title: "Update score.yaml with storage type s3"
        body: "This PR updates the score.yaml file with a new storage configuration: S3."
        labels: update, score.yaml
